language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends check valgrind

script:
  - autoreconf -i
  - ./configure
  - make -j2 memcheck
  - make distcheck

env:
  global:
    - secure: "FCsDw8O0O29KWWuuVmOY2FuJ0/8ij3YU5QqCV2M35Mfw8QQuOoNX0KcQFXRMuYLnWUuzDFNyPi8Gui8r//X1hh9DAjt3RQmMMqueF0fq5Pi8Pyetw3AAf7dpyswXD3G8XhjM0cZSVwa2tQRZVvFa6MIL5bPfvNWQqchSJwAfapw="

addons:
  coverity_scan:
    project:
      name: "msteinert/bstring"
    notification_email: mike.steinert@gmail.com
    build_command_prepend: autoreconf -if && ./configure
    build_command: make -j4
    branch_pattern: coverity_scan
